### ISSUE TITLE
Missing Files/Functions

### ISSUE THREAD

**Issue by MingleiGitHub** [stochastic-geometry/DPPL#1]
Hi!

I am trying to run the code but it seems there are some missing files or functions, for example the "parameters" in the trainDPP.m. 

Thank you for your time.

Best regards,
Ming

**Comment by stochastic-geometry** [comment]
Hi Ming
  Thanks for reporting the issue. It seems that the file was missing during the initial commit. We have added the file "parameters.m". The code should run fine now. 

Thanks
Chiranjib
